### PR TITLE
OAuth2Authenticator.getOAuth2TokenPair() is unable to use refresh token

### PR DESCRIPTION
**Pull request by maartenba**
See #15 for full explanation

### CODE REVIEW

**Comment by davidstaheli** [comment]
Hi @maartenba, to get the Travis CI build working, can you please merge master into your branch, or simply change the file **/.travis.yml** so that the jdk line is `oraclejdk8` instead of `openjdk6`?

**Comment by maartenba** [comment]
Done, awaiting build to complete now.

**Comment by maartenba** [comment]
Thanks @DavidStaheli ! Any chance of getting an updated artifact pushed up to Maven Central?

**Comment by davidstaheli** [comment]
Hi @maartenba, yes, I hope we can do that today.  It's been a while so we're bringing the process back to life.  :)

**Comment by maartenba** [comment]
@DavidStaheli Any news on the Maven artifacts? :-)

**Comment by AndreyAkinshin** [comment]
@DavidStaheli, could you please update the Maven package? We really need it.

**Comment by maartenba** [comment]
Any news here?

**Comment by davidstaheli** [comment]
Working on it.  Hoping to have more information imminently.

**Comment by davidstaheli** [comment]
Fingers crossed, it should be released tonight.

**Comment by yacaovsnc** [comment]
[0.6.4](https://repo1.maven.org/maven2/com/microsoft/alm/auth-lib-parent/0.6.4/) released to maven central.

**Comment by maartenba** [comment]
Great, thanks so much!

**Pull request merged**
